### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by davemclaughlin** [Holger-Will/node-enocean#15]
I am trying to use your node with a wrapper from someone else and I am seeing the following error when I start Node-red. I have a Raspberry Pi3 with Enocean PI and configured for ttyS0. This causes Node-red to crash repeatedly and I have to stop it, edit the flow file to remove the node and then restart it. 

22 Oct 14:17:46 - [red] Uncaught Exception:
22 Oct 14:17:46 - TypeError: offset is not uint
at TypeError (<anonymous>)
at checkInt (buffer.js:786:11)
at Buffer.writeInt16BE (buffer.js:908:5)
at ESP3Packet.getRawBuffer (/home/pi/.node-red/node_modules/serialport-enocean-parser/ESP3Packet.js:56:20)
at SerialPortListener.<anonymous> (/home/pi/.node-red/node_modules/node-enocean/index.js:73:23)
at SerialPort.emit (events.js:95:17)
at emitFetchedESP3Packet (/home/pi/.node-red/node_modules/serialport-enocean-parser/ESP3Parser.js:144:11)
at fetchCRC8ForDataAndCheck (/home/pi/.node-red/node_modules/serialport-enocean-parser/ESP3Parser.js:134:3)
at ESP3.tryToFillPackets (/home/pi/.node-red/node_modules/serialport-enocean-parser/ESP3Parser.js:29:4)
at Object.module.exports [as parser](/home/pi/.node-red/node_modules/serialport-enocean-parser/ESP3Parser.js:14:7)
at SerialPort.settings.dataCallback (/home/pi/.node-red/node_modules/node-enocean/node_modules/serialport/lib/serialport.js:147:14)
at SerialPort._emitData (/home/pi/.node-red/node_modules/node-enocean/node_modules/serialport/lib/serialport.js:350:18)
at SerialPort.<anonymous> (/home/pi/.node-red/node_modules/node-enocean/node_modules/serialport/lib/serialport.js:330:14)
at SerialPort.<anonymous> (/home/pi/.node-red/node_modules/node-enocean/node_modules/serialport/lib/serialport.js:343:7)
at Object.wrapper [as oncomplete](fs.js:463:17)
nodered.service: main process exited, code=exited, status=1/FAILURE

**Comment by RafaelKa** [comment]
It seems that you are using Node v. 0.10. Could you please try it on newer node engine?

**Comment by RafaelKa** [comment]
@davemclaughlin or try to change:
 
[dataLengthBuffer.writeInt16BE(this.header.dataLength)](https://github.com/RafaelKa/node-serialport-enocean-parser/blob/d9bdb93f3e3518362cfd65e1d8b86775f8e1c6a4/ESP3Packet.js#L56)

to 

```
dataLengthBuffer.writeInt16BE(this.header.dataLength, 0);
```
and let me please know if it solves this issue on Node v. <=0.11

**Comment by davemclaughlin** [comment]
That works. Thanks for the quick fix.

**Comment by RafaelKa** [comment]
@davemclaughlin what exactly works :D. There are multiple solutions mentined!

**Comment by davemclaughlin** [comment]
Sorry, this one.

dataLengthBuffer.writeInt16BE(this.header.dataLength, 0);
